generateRandomNumber 1
rememberPheromone 1
goto
if then
eatFood
bite
moveForward
pickUpFood
dropFood
emitPheromone 1
faceRandomDirection
rotateClockwise
rotateCounterClockwise

last_random_number_was_zero
last_pheromone_stronger
same_pheromone_type
i_am_carrying_food
i_am_hungry
i_am_standing_with_an_enemy
i_am_standing_on_food
i_am_standing_on_my_anthill
i_smell_pheromone_in_front_of_me
i_smell_danger_in_front_of_me
i_was_bit
i_was_blocked_from_moving
